imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    translator:      { fallback: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 1.0.0
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - BraincraftedBootstrapBundle:Form:bootstrap.html.twig
    globals:
        brand: QuickStart
        nocaptcha_site_key: %nocaptcha_site_key%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
       lessphp:
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: "\.less$"
       cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# BootstrapBundle Configuration
braincrafted_bootstrap:
    jquery_path: %kernel.root_dir%/../src/Fuz/QuickStartBundle/Resources/public/js/jquery-2.1.1.min.js
    less_filter: lessphp
    auto_configure:
      knp_menu: false

# cache cleaning
accelerator_cache:
    host: %site_url%
    web_dir: %kernel.root_dir%/../web
    mode: curl

# HWIOAuthBundle Configuration
hwi_oauth:
    firewall_name: main
    connect:
        confirmation: false
    resource_owners:
        google:
            type: google
            client_id: %google_client_id%
            client_secret: %google_secret%
            scope: "profile"
            options:
                display: page
                access_type: online
                approval_prompt: force
                login_hint: email address
        facebook:
            type: facebook
            client_id: %facebook_client_id%
            client_secret: %facebook_secret%
            scope: "public_profile"
            options:
                display: page
        twitter:
            type: twitter
            client_id: %twitter_client_id%
            client_secret: %twitter_secret%
            scope: ""

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Fuz\QuickStartBundle\Entity\User

# Supported Website Languages
jms_i18n_routing:
    default_locale: en
    locales: [en, fr]
    strategy: prefix_except_default

# KnpMenu template configuration
knp_menu:
    twig:
        template: FuzQuickStartBundle::knp_menu.html.twig

# Common tools Configuration
fuz_quick_start:
    no_captcha:
        check_url: https://www.google.com/recaptcha/api/siteverify
        post_param: g-recaptcha-response
        site_key: %nocaptcha_site_key%
        secret_key: %nocaptcha_secret_key%
        sessions_per_ip: { max: 20, delay: 3600 }
        strategies:
            fos_user_registration_register: { hits: 1, delay: 60 }
            fos_user_security_check: { hits: 5, delay: 60 }
