parameters:
    app.menu.main_left.class: AppBundle\Menu\Builder
    app.menu.main_right.class: AppBundle\Menu\Builder
    app.menu.user_left.class: AppBundle\Menu\Builder
    app.menu.user_right.class: AppBundle\Menu\Builder

services:
    app.menu.main_left:
        class: '%app.menu.main_left.class%'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: knp_menu.menu, method: mainLeftMenu, alias: main_left }

    app.menu.main_right:
        class: '%app.menu.main_right.class%'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: knp_menu.menu, method: mainRightMenu, alias: main_right }

    app.menu.user_left:
        class: '%app.menu.user_left.class%'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: knp_menu.menu, method: userLeftMenu, alias: user_left }

    app.menu.user_right:
        class: '%app.menu.user_right.class%'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: knp_menu.menu, method: userRightMenu, alias: user_right }
